// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  Timestamp,
  Timestamptz,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma-next/target-postgres/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ContractModelDefinitions,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:147438078aa4658308daa6260b8f1f3f76f235d017ebe0b3161e62a7b85eafb9'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:e680a0bc5cdf975c7992f3306afd113d6d40141002f1b6559d9ea13e489f8203'>;
export type ProfileHash =
  ProfileHashBase<'sha256:9c8aa3114e84ed3b7ea2bd57526d9c2e1bf7c5292be694e9d3801f566fda7ccb'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Event: {
    readonly id: Char<36>;
    readonly workspaceId: CodecTypes['pg/text@1']['output'];
    readonly actorId: CodecTypes['pg/text@1']['output'] | null;
    readonly kind: CodecTypes['pg/text@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly Event: {
    readonly id: CodecTypes['sql/char@1']['input'];
    readonly workspaceId: CodecTypes['pg/text@1']['input'];
    readonly actorId: CodecTypes['pg/text@1']['input'] | null;
    readonly kind: CodecTypes['pg/text@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = Omit<
  ContractType<
    {
      readonly namespaces: {
        readonly __unbound__: {
          readonly id: '__unbound__';
          readonly kind: 'postgres-unbound-schema';
          readonly entries: { readonly table: {}; readonly type: Record<string, never> };
        };
        readonly public: {
          readonly id: 'public';
          readonly kind: 'postgres-schema';
          readonly entries: {
            readonly table: {
              readonly Event: {
                columns: {
                  readonly id: {
                    readonly nativeType: 'character';
                    readonly codecId: 'sql/char@1';
                    readonly nullable: false;
                    readonly typeParams: { readonly length: 36 };
                  };
                  readonly workspaceId: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: false;
                  };
                  readonly actorId: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: true;
                  };
                  readonly kind: {
                    readonly nativeType: 'text';
                    readonly codecId: 'pg/text@1';
                    readonly nullable: false;
                  };
                  readonly createdAt: {
                    readonly nativeType: 'timestamptz';
                    readonly codecId: 'pg/timestamptz@1';
                    readonly nullable: false;
                    readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  };
                };
                primaryKey: { readonly columns: readonly ['id'] };
                uniques: readonly [];
                indexes: readonly [];
                foreignKeys: readonly [];
              };
            };
            readonly type: Record<string, never>;
          };
        };
      };
      readonly storageHash: StorageHash;
    },
    {
      readonly Event: {
        readonly fields: {
          readonly id: {
            readonly nullable: false;
            readonly type: {
              readonly kind: 'scalar';
              readonly codecId: 'sql/char@1';
              readonly typeParams: { readonly length: 36 };
            };
          };
          readonly workspaceId: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly actorId: {
            readonly nullable: true;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly kind: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
          };
          readonly createdAt: {
            readonly nullable: false;
            readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
          };
        };
        readonly relations: Record<string, never>;
        readonly storage: {
          readonly table: 'Event';
          readonly namespaceId: 'public';
          readonly fields: {
            readonly id: { readonly column: 'id' };
            readonly workspaceId: { readonly column: 'workspaceId' };
            readonly actorId: { readonly column: 'actorId' };
            readonly kind: { readonly column: 'kind' };
            readonly createdAt: { readonly column: 'createdAt' };
          };
        };
      };
    }
  >,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Event: { readonly namespace: 'public' & NamespaceId; readonly model: 'Event' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Event: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/char@1';
                  readonly typeParams: { readonly length: 36 };
                };
              };
              readonly workspaceId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly actorId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'Event';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly workspaceId: { readonly column: 'workspaceId' };
                readonly actorId: { readonly column: 'actorId' };
                readonly kind: { readonly column: 'kind' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'Event'; readonly column: 'id' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv7' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Models = ContractModelDefinitions<Contract>;

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
